#ifndef GSH_H
#define GSH_H
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <fcntl.h> 
#include <errno.h>
#include <pwd.h>
#include <signal.h>
#include <sys/wait.h>
#include <sys/types.h>
#include <sys/stat.h> 
#include "prompt.h"
#include "read.h"
#include "run.h"
#include "builtin.h"
#endif
